Add new post - Rocky Linux 8.4 GA Available Now
rockylinuxtw/rockylinux.tw pull request #32
Opened 2021-06-24 14:57 UTC by steveyiyo

2021-06-25 23:36 UTC, lekoOwO commented on blogs/rocky-linux-8-4-ga-release.md
> +
Where's the table?

2021-06-26 07:25 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +- Container Images
容器映像檔

2021-06-26 07:30 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +
我不太了解表格要如何顯示在 MarkDown 裡面，晚點會在討論如何處理。

2021-07-11 01:33 UTC, evshary requested changes

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +我們也在以下提供內容：
也許可翻成：以下是目前可用的資源

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +- Cloud Offerings
或許可翻成：雲端資源

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +商業化的利益是短暫並且自私的，但社群任然存在，這就是我們要將 Rocky Linux 所奉獻的給的人：您
建議：社群能長期存在
後半句有點難翻，也許可以這樣：並將 Rocky Linux 呈現給您

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +Rocky 不僅僅是下一個免費開源的社群企業操作系統，同時也是一個社群。
作業系統

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +這些企業都為社群帶來一些特別的東西，我們非常感謝他們的協助！
"特別的貢獻"會比較好些

2021-07-11 01:33 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +
MarkDown也可以產生表格，可以試試這個：https://www.tablesgenerator.com/markdown_tables

2021-07-11 22:28 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +最後，這只是一個開始，RESF 不僅僅是 Rocky Linux，對於那些相信開源不僅是一個可以隨意切換的開關，而且許多人依賴的項目不會受制於少數人的心血來潮的人來說，這是一個家。
這邊我有點沒想法，你們有想法嗎？
“
最後，這只是一個開始。  
RESF 不僅僅是 Rocky Linux，對於那些相信開源不僅是一個可以隨意切換的開關，而且許多人依賴的項目不會受制於少數人的心血來潮的人來說，這是一個家。
”

2021-07-12 11:39 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +
Thanks @evshary

2021-07-12 11:48 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +在接下來的幾周和幾個月內，RESF 預計會提供更多信息。
在哪邊 XD

2021-07-12 15:21 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +最後，這只是一個開始，RESF 不僅僅是 Rocky Linux，對於那些相信開源不僅是一個可以隨意切換的開關，而且許多人依賴的項目不會受制於少數人的心血來潮的人來說，這是一個家。
這句真的不好翻，看這樣如何：
這是一個開始，而 RESF 不僅僅是 Rocky Linux — 對那些相信開源不是隨意切換的開關，而且專案不能依賴少數人心血來潮的人來說，它是一個家。

2021-07-12 15:22 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +在接下來的幾周和幾個月內，RESF 預計會提供更多信息。
應該是說"訊息"吧

2021-07-12 15:27 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +“ 我們著手開發一個免費開源的社群企業操作系統，該操作系統與上游企業 Linux 標準兼容。我們同時還建構一個社群。”
這邊應該要用作業系統。
然後最後一句可以改成：不僅如此，我們所打造的是，一個社群。

2021-07-12 15:30 UTC, evshary commented on blogs/rocky-linux-8-4-ga-release.md
> +最後，這只是一個開始，RESF 不僅僅是 Rocky Linux，對於那些相信開源不僅是一個可以隨意切換的開關，而且許多人依賴的項目不會受制於少數人的心血來潮的人來說，這是一個家。
話說如果真的沒想法，也可以參考中國那邊的翻譯，不過用詞要注意改成台灣的就是了
https://rockylinux.cn/rocky-linux-84-is-officially-released.html#more

2021-07-12 21:14 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +在接下來的幾周和幾個月內，RESF 預計會提供更多信息。
我這邊改成了 “資訊”
> 在接下來的幾周和幾個月內，RESF 預計會提供更多資訊。

2021-07-12 21:15 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +“ 我們著手開發一個免費開源的社群企業操作系統，該操作系統與上游企業 Linux 標準兼容。我們同時還建構一個社群。”
Done, Thanks

2021-07-12 22:02 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +到目前為止，您可以輕鬆找到我們所有的原始程式碼、基礎設施、Git 存儲庫及任何人需要 Fork 我們的工作，並確保在需要時繼續進行的所有內容。
我這邊沒想法了。
剛剛參考了一下 [Rocky Linux 中文社区](https://rockylinux.cn/) 的文章 - [Rocky Linux 8.4 正式版发布啦](https://rockylinux.cn/rocky-linux-84-is-officially-released.html#more)，感覺沒什麼太大問題？

2021-07-12 22:03 UTC, steveyiyo commented
Everything has been resolved, please review again @lekoOwO @evshary .
Thanks <3

2021-07-12 23:24 UTC, evshary approved these changes
LGTM

2021-07-12 23:33 UTC, lekoOwO requested changes

2021-07-12 23:33 UTC, lekoOwO commented on blogs/rocky-linux-8-4-ga-release.md
> +現在，我們希望您提供共多支援：加入我們，共同建立我們的社區。
錯字

2021-07-12 23:33 UTC, lekoOwO commented on blogs/rocky-linux-8-4-ga-release.md
> +
這裡少一段 Release Party

2021-07-12 23:33 UTC, lekoOwO commented on blogs/rocky-linux-8-4-ga-release.md
> +社群能長期存在，並將 Rocky Linux 呈現給您
這句前面應該也還有東西

2021-07-12 23:39 UTC, lekoOwO commented on blogs/rocky-linux-8-4-ga-release.md
> +社群能長期存在，並將 Rocky Linux 呈現給您
企業逐利而去，而社群永存，並在此為您獻上 Rocky Linux。

之類的
或看你想怎麼翻

2021-07-12 23:50 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +
新內容

2021-07-12 23:54 UTC, steveyiyo commented on blogs/rocky-linux-8-4-ga-release.md
> +社群能長期存在，並將 Rocky Linux 呈現給您
Nice. 這邊意思就是在指企業是以利益為優先，而社群不是。
我有個更好的想法。

> 相較於 以利益為優先的企業，我們永遠存在，在此為您獻上 Rocky Linux。

2021-07-13 02:46 UTC, lekoOwO approved these changes

2021-07-13 02:46 UTC, merged