Add New Post - Community Update - June 2021
rockylinuxtw/rockylinux.tw pull request #34
Opened 2021-07-13 03:37 UTC by steveyiyo

2021-07-13 03:37 UTC, steveyiyo commented
Please also check the translation of the following.

> their sponsorship ensures Rocky’s status as a first-class citizen on the Google Cloud Platform from day one, with supported images immediately available for launch.

> 他們的贊助確保了 Rocky 成為 Google Cloud Platform 上的一等公民，並立即提供支援的圖像以供發布。 

> To say that Rocky Linux 8.4 is popular would be an understatement.
> You, the community, made this happen. We can’t begin to express our gratitude for your support. Watching the community grow from a comment in a blog post in December to what it is today, with teams around the world working on documentation, development, branding, security, infrastructure, and more, has been one of the most rewarding and humbling experiences we’ve ever been a part of.

> 說 Rocky Linux 8.4 很受歡迎，其實是輕描淡寫。 
> 整個社群（包括你），讓這一切成真了！  
> 我們無法開始對您的支援表示感謝。看著社群從 12 月的一篇部落格文章中發展到現在，來自世界各地的團隊致力於文件、開發、品牌、安全及基礎建設等，一直是我們參與過最有價值及最謙卑的經歷之一。

2021-07-13 07:21 UTC, pwtsai commented
GCP has added Rocky Linux as an option in OS list. I suggest to make a small change like: 
"他們的贊助確保了 Rocky Linux 成為提供給 Google Cloud Platform 客戶的最優質選擇，並立即新增了代表圖示。"
Please correct me if I misunderstood the original meaning.

2021-07-13 10:27 UTC, steveyiyo commented
@pwtsai Looks good, Thanks!

2021-07-15 15:41 UTC, evshary requested changes

2021-07-15 15:41 UTC, evshary commented on blogs/community-update-june-2021.md
> +與此同時，Microsoft 也簽約成為 RESF 的合作夥伴！以下內容來自他們：
以下內容來自他們： => 他們表示：

2021-07-15 15:41 UTC, evshary commented on blogs/community-update-june-2021.md
> +說 Rocky Linux 8.4 很受歡迎，其實是輕描淡寫。
用受歡迎來形容 Rocky Linux 8.4 都太過輕描淡寫了。

2021-07-15 15:41 UTC, evshary commented on blogs/community-update-june-2021.md
> +我們收到了一些來自社群的關於 RESF 結構的問題，雖然這些內容一直在我們的網站上可用，但保險起見，我們進行了更新。
雖然這些內容一直在我們的網站上可用，但保險起見，我們進行了更新 => 雖然這些資訊在網站上一直都能查詢到，但我們還是做了更明確的更新

2021-07-15 15:41 UTC, evshary commented on blogs/community-update-june-2021.md
> +順頌時祺
這個有點翻法有點奇妙，不知道謹啟會不會比較好一些
不然乾脆不要翻

2021-07-16 22:12 UTC, steveyiyo commented on blogs/community-update-june-2021.md
> +順頌時祺
Sincerely to "謹啟", Thanks!

2021-07-16 22:19 UTC, steveyiyo commented
@evshary Please review it again, Thanks!

2021-07-16 23:54 UTC, evshary approved these changes

2021-07-24 07:51 UTC, steveyiyo commented
@gnehs Ping.
If you have free time, please check and approve.
Thanks

2021-07-24 08:23 UTC, gnehs approved these changes

2021-07-24 11:49 UTC, merged